#Big Data
#Assignment 1
##202318042

##Task A

In [ ]:
import numpy as np

In [ ]:
n=int(input("size of your square matrix:"))

size of your square matrix:2


In [ ]:
#making a matrix A with dimension (2n X 2n)
A=np.random.randint(5, size=(2*n, 2*n))
print(f"let the first matrix be:\n{A}")

let the first matrix be:
[[3 0 4 3]
 [2 1 0 1]
 [2 4 0 3]
 [2 1 4 0]]


In [ ]:
#making a matrix B with dimension (2n X 2n)
B=np.random.randint(5,9, size=(2*n, 2*n))
print(f"let the second matrix be:\n{B}")

let the second matrix be:
[[6 8 5 8]
 [6 7 5 8]
 [7 6 5 7]
 [7 8 6 6]]


In [ ]:
block_size=2

In [ ]:
def block_multiply(A, B,block_size):

    size = len(A)
    result = [[0 for _ in range(size)] for _ in range(size)]

    for i in range(0, size, block_size):
        for j in range(0, size, block_size):
            for k in range(0, size, block_size):
                for ii in range(i, i + block_size):
                    for jj in range(j, j + block_size):
                        for kk in range(k, k + block_size):
                            result[ii][jj] += A[ii][kk] * B[kk][jj]

    return result

In [ ]:
ans=block_multiply(A, B,block_size)

In [ ]:
print(ans)

[[67, 72, 53, 70], [25, 31, 21, 30], [57, 68, 48, 66], [46, 47, 35, 52]]


In [ ]:
#doing normal matrix multiplication
def matrix_multiply(A, B):

    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    return result

In [ ]:
 tester=matrix_multiply(A, B)
 print(tester)

[[67, 72, 53, 70], [25, 31, 21, 30], [57, 68, 48, 66], [46, 47, 35, 52]]
